site_name: CS153 Design of Operating System - Lab Session
site_url: http://gdjs2.cn/UCR-CS153-25Winter/
site_description: Lab Session for CS153 Design of Operating System
site_author: Zhaoqi Xiao

theme:
  name: material
  palette:
    primary: teal
    accent: teal
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - content.code.annotate

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details

copyright: Copyright &copy; 2025 Zhaoqi Xiao. All rights reserved.

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  